include $(SRCTREE)/common_files/base.mk
TOP_CONFIG_FILE ?=
#
include $(TOP_CONFIG_FILE)

all:
clean:
clean_all:
install:
	chmod 777 *.sh
	mkdir -p $(INSTALL_PATH)/bin/test_scripts
	cp *.sh $(INSTALL_PATH)/bin/test_scripts