#ifndef FLASH_ERROR_H
#define FLASH_ERROR_H

typedef enum ERROR_TYPE {
    FLASH_OK,
    FLASH_PARAM_ERROR,
    FLASH_MM_ERROR,
    FLASH_IO_ERROR,
    FLASH_FS_ERROR,
    FLASH_UNKNOWN_ERROR
} ERROR_TYPE;

#endif /* FLASH_ERROR_H */
