#ifndef __MODE_H__
#define __MODE_H__
#include <pthread.h>
#include "appcomm.h"
#include "sysutils_hfsm.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

typedef enum _WORK_MODE_E
{
    WORK_MODE_MOVIE,
    WORK_MODE_PHOTO,
    WORK_MODE_PLAYBACK,
    WORK_MODE_USBCAM,
    WORK_MODE_USB,
    WORK_MODE_UPDATE,
    WORK_MODE_LAPSE,
    WORK_MODE_UVC,
    WORK_MODE_STORAGE,
    WORK_MODE_BOOT,
    WORK_MODE_USBMENU,
    WORK_MODE_BUTT
} WORK_MODE_E;

typedef enum _MEDIA_MOVIE_MODE_E
{
    MEDIA_MOVIE_STATE_VIEW,
    MEDIA_MOVIE_STATE_REC,
    MEDIA_MOVIE_STATE_LAPSE_REC,
    MEDIA_MOVIE_STATE_MENU,
    MEDIA_MOVIE_STATE_BUTT
} MEDIA_MOVIE_MODE_E;

typedef enum _MEDIA_PHOTO_STATE_E
{
    MEDIA_PHOTO_STATE_VIEW,
    MEDIA_PHOTO_STATE_MENU,
    MEDIA_PHOTO_STATE_BUTT
} MEDIA_PHOTO_STATE_E;

typedef enum _MEDIA_PLAYBACK_STATE_E
{
    MEDIA_PLAYBACK_STATE_VIEW,
    MEDIA_PLAYBACK_STATE_PLAY,
    MEDIA_PLAYBACK_STATE_PAUSE,
    MEDIA_PLAYBACK_STATE_MENU,
    MEDIA_PLAYBACK_STATE_ABNORMAL,
    MEDIA_PLAYBACK_STATE_BUTT
} MEDIA_PLAYBACK_STATE_E;

/** exit mode */
typedef enum EXIT_MODE_E
{
    MODEMNG_EXIT_MODE_POWEROFF,
    MODEMNG_EXIT_MODE_REBOOT,
    MODEMNG_EXIT_MODE_SERVICE_QUIT,
    MODEMNG_EXIT_MODE_BUTT
} MODEMNG_EXIT_MODE_E;

typedef enum _CARD_STATE_E
{
    CARD_STATE_REMOVE,
    CARD_STATE_AVAILABLE,
    CARD_STATE_UNAVAILABLE,
    CARD_STATE_ERROR,
    CARD_STATE_FSERROR,
    CARD_STATE_CHECKING,
    CARD_STATE_SLOW,
    CARD_STATE_FORMATED,
    CARD_STATE_READ_ONLY,
    CARD_STATE_MOUNT_FAILED,
    CARD_STATE_FULL_SPACE,
    CARD_STATE_BUIT
} CARD_STATE_E;

/** exit mode callback */
typedef int32_t (*MODEMNG_EXIT_MODE_CALLBACK)(MODEMNG_EXIT_MODE_E enExitMode);

/** statemng configure */
typedef struct PDT_MODEMNG_CONFIG_S
{
    MODEMNG_EXIT_MODE_CALLBACK pfnExitCB;
} MODEMNG_CONFIG_S;

/** modemng context */
typedef struct _MODEMNG_S {
    bool                bInited;
    pthread_mutex_t     Mutex;/**<Mutex for bInProgress*/
    HFSM_HANDLE     pvHfsmHdl;
    STATE_S         stBase;
    WORK_MODE_E     CurWorkMode;
    bool                bInProgress;
    bool                bInEmrRec;
    bool                bInParkingRec;
    bool                bSysPowerOff;
    uint8_t             u32ModeState;
    uint8_t             u32CardState;
    MODEMNG_CONFIG_S stModemngCfg;
} MODEMNG_S;

#define MODE_EINITIALIZED      APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_EINITIALIZED)/**<Initialized already */
#define MODE_ENOTINIT          APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_ENOINIT)/**<Not inited */
#define MODE_EINVAL            APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_EINTER)/**<Parameter invalid */
#define MODE_EINTER            APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_EINTER)/**<Internal error */
#define MODE_ENULLPTR          APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_ERRNO_CUSTOM_BOTTOM + 1)/**<Null pointer */
#define MODE_EINPROGRESS       APP_APPCOMM_ERR_ID(APP_MOD_MODEMNG,APP_ERRNO_CUSTOM_BOTTOM + 2)/**<Operation now in progress */
typedef enum EVENT_MODE_E {
    EVENT_MODEMNG_CARD_REMOVE               = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 0),
    EVENT_MODEMNG_CARD_AVAILABLE            = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 1),
    EVENT_MODEMNG_CARD_UNAVAILABLE          = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 2),
    EVENT_MODEMNG_CARD_ERROR                = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 3),
    EVENT_MODEMNG_CARD_FSERROR              = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 4),
    EVENT_MODEMNG_CARD_SLOW                 = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 5),
    EVENT_MODEMNG_CARD_CHECKING             = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 6),
    EVENT_MODEMNG_CARD_FORMAT,
    EVENT_MODEMNG_CARD_FORMATING,
    EVENT_MODEMNG_CARD_FORMAT_SUCCESSED,
    EVENT_MODEMNG_CARD_FORMAT_FAILED,
    EVENT_MODEMNG_CARD_READ_ONLY,
    EVENT_MODEMNG_CARD_MOUNT_FAILED,
    EVENT_MODEMNG_RESET,
    EVENT_MODEMNG_MODESWITCH,
    EVENT_MODEMNG_MODEOPEN,
    EVENT_MODEMNG_MODECLOSE,
    EVENT_MODEMNG_START_REC,
    EVENT_MODEMNG_STOP_REC,
    EVENT_MODEMNG_SWITCH_LIVEVIEW,
    EVENT_MODEMNG_LIVEVIEW_UPORDOWN,
    EVENT_MODEMNG_LIVEVIEW_ADJUSTFOCUS,
    EVENT_MODEMNG_START_PIV,
    EVENT_MODEMNG_SMILE_START_PIV,
    EVENT_MODEMNG_START_EMRREC,
    EVENT_MODEMNG_SCREEN_DORMANT,
    EVENT_MODEMNG_SETTING,
    EVENT_MODEMNG_SETTING_LANGUAGE,
    EVENT_MODEMNG_POWEROFF,
    EVENT_MODEMNG_PLAYBACK_PLAY             = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 100),
    EVENT_MODEMNG_PLAYBACK_PROGRESS,
    EVENT_MODEMNG_PLAYBACK_PAUSE,
    EVENT_MODEMNG_PLAYBACK_RESUME,
    EVENT_MODEMNG_PLAYBACK_SEEK,
    EVENT_MODEMNG_PLAYBACK_SEEKPAUSE,
    EVENT_MODEMNG_PLAYBACK_FINISHED,
    EVENT_MODEMNG_PLAYBACK_ABNORMAL,
    EVENT_MODETEST_START_RECORD             = APPCOMM_EVENT_ID(APP_MOD_MODEMNG, 200),
    EVENT_MODETEST_STOP_RECORD,
    EVENT_MODETEST_PLAY_RECORD,
    EVENT_MODEMNG_START_UPFILE,
    EVENT_MODEMNG_UPFILE_SUCCESSED,
    EVENT_MODEMNG_UPFILE_FAIL,
    EVENT_MODEMNG_UPFILE_FAIL_FILE_ERROR,
    EVENT_MODEMNG_UVC_MODE_START,
    EVENT_MODEMNG_UVC_MODE_STOP,
    EVENT_MODEMNG_STORAGE_MODE_PREPAREDEV,
    EVENT_MODEMNG_PHOTO_SET,
    EVENT_MODEMNG_FOCUS,
    EVENT_MODEMNG_PHOTO_STARTPIVSTAUE,
    EVENT_MODEMNG_RTSP_INIT,
    EVENT_MODEMNG_RTSP_SWITCH,
    EVENT_MODEMNG_RTSP_DEINIT,
    EVENT_MODEMNG_RECODER_STARTSTATU,
    EVENT_MODEMNG_RECODER_STOPSTATU,
    EVENT_MODEMNG_RECODER_SPLITREC,
    EVENT_MODEMNG_RECODER_STARTEVENTSTAUE,
    EVENT_MODEMNG_RECODER_STOPEVENTSTAUE,
    EVENT_MODEMNG_RECODER_STARTEMRSTAUE,
    EVENT_MODEMNG_RECODER_STOPEMRSTAUE,
    EVENT_MODEMNG_RECODER_STARTPIVSTAUE,
    EVENT_MODEMNG_RECODER_STOPPIVSTAUE,
    EVENT_MODEMNG_SENSOR_STATE,
#ifdef SERVICES_SPEECH_ON
    EVENT_MODEMNG_SPEECHMNG_STARTREC,
    EVENT_MODEMNG_SPEECHMNG_STOPREC,
    EVENT_MODEMNG_SPEECHMNG_OPENFRONT,
    EVENT_MODEMNG_SPEECHMNG_OPENREAR,
    EVENT_MODEMNG_SPEECHMNG_CLOSESCREEN,
    EVENT_MODEMNG_SPEECHMNG_OPENSCREEN,
    EVENT_MODEMNG_SPEECHMNG_EMRREC,
    EVENT_MODEMNG_SPEECHMNG_PIV,
    EVENT_MODEMNG_SPEECHMNG_CLOSEWIFI,
    EVENT_MODEMNG_SPEECHMNG_OPENWIFI,
    EVENT_MODEMNG_START_SPEECH,
    EVENT_MODEMNG_STOP_SPEECH,
#endif
    EVENT_MODEMNG_BUTT
} EVENT_MODE_E;

int32_t MODEMNG_Init(MODEMNG_CONFIG_S *stModemngCfg);
int32_t MODEMNG_Deinit();
int32_t MODEMNG_SendMessage(const MESSAGE_S *pstMsg);
int32_t MODEMNG_GetCurMode(uint32_t *ModeId);
int32_t MODEMNG_GetCurWorkMode(void);
int32_t MODEMNG_SetParkingRec(bool en);
int32_t MODEMNG_GetModeState(uint32_t *state);
int32_t MODEMNG_SetModeState(uint32_t state);
int32_t MODEMNG_RegisterEvent(void);
int32_t MODEMNG_LiveViewUp(uint32_t viewwin);
int32_t MODEMNG_LiveViewDown(uint32_t viewwin);
int32_t MODEMNG_SetSensorState(uint32_t state);
int32_t MODEMNG_GetSensorState(uint32_t *state);

uint32_t MODEMNG_GetCardState(void);
bool MODEMNG_SetCardState(uint32_t u32CardState);

bool MODEMNG_GetInProgress(void);
bool MODEMNG_GetEmrState(void);

int32_t MODEMNG_TEST_MAIN_Create(void);
int32_t MODEMNG_TEST_MAIN_Destroy(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif
