; ============= USB WorkMode =================
[common]
work_mode          = "usb"
usb_mode           = 1; 0:charge, 1:uvc, 2:storage
; ============= UVC Configure =============
[config0]
cam_id             = 0
media_mode         = "record_1440p25"

[config1]
cam_id             = 1
media_mode         = "record_1080p25"

[uvc]
dev_path           = "/dev/video1";
[yuv420]
count              = 1
video_mode0        = 0; 0:VGA30
video_defmode      = 0; 0:VGA30
[mjpeg]
count              = 3
video_mode0        = 0; 0:VGA30
video_bitrate0     = 20480;
video_mode1        = 1; 1:720P30
video_bitrate1     = 20480;
video_mode2        = 2; 2:1080P30
video_bitrate2     = 40960;
video_defmode      = 1; 1:720P30
[h264]
count              = 3
video_mode0        = 0; 0:VGA30
video_bitrate0     = 20480;
video_mode1        = 1; 1:720P30
video_bitrate1     = 20480;
video_mode2        = 2; 2:1080P30
video_bitrate2     = 40960;
video_defmode      = 1; 1:720P30

[datasource]
vcap_id            = 0
vporc_id           = 0
vporc_chn_id       = 0
acap_id            = 0

[buffer]
buffer_size        = 3110400; 1920*1080*1.5
buffer_count       = 6; >= 6

; ============= USB Storage Configure =============
[storage]
dev_path           = "/dev/mmcblk0p1";
sysfile            = "123";
usb_state_proc     = "/sys/devices/platform/4340000.usb/udc/4340000.usb/state";
