; common config
[common]
mount_point = "/mnt/sd"
root_path = "DCIM"
formated_flag = "cvi_sdconfig"
reserved_space_percent = 5
deleted_space_percent = 5


[stream.dir]
cnt = 1

[stream0.dir]
normal_dir = "MOVIE"      ; main stream
normal_filesuffix = ""      ; filename suffix, ex: 20230807161900_F.MOV. suffix is "_F"
normal_percent = 40         ; The percentage of available space occupied by the main stream
normal_prealloc_size = 100  ; Main stream preallocation size (MB)
normal_align_size = 20      ; Main stream alignment size (MB)
normal_s_dir = ""           ; sub stream
normal_s_filesuffix = ""    ; filename suffix, ex: 20230807161900_S.MOV. suffix is "_S"
normal_s_percent =          ; The percentage of available space occupied by the sub stream
normal_s_prealloc_size =    ; sub stream preallocation size (MB)
normal_s_align_size =       ; sub stream alignment size (MB)
park_dir = ""               ; parking monitoring main stream
park_filesuffix = ""        ; filename suffix, ex: 20230807161900_F.MOV. suffix is "_F"
park_percent =              ; The percentage of available space occupied by the parking monitoring
park_prealloc_size =        ; parking monitoring stream preallocation size (MB)
park_align_size =           ; parking monitoring alignment size (MB)
park_s_dir = ""             ; parking monitoring sub stream
park_s_filesuffix = ""      ; filename suffix, ex: 20230807161900_F.MOV. suffix is "_F"
park_s_percent =            ; The percentage of available space occupied by the parking monitoring sub stream
park_s_prealloc_size =      ; parking monitoring sub stream preallocation size (MB)
park_s_align_size =         ; parking monitoring sub stream alignment size (MB)
photo_dir = "PHOTO"       ; snap
photo_filesuffix = ""       ; filename suffix, ex: 20230807161900_F.Jpeg. suffix is "_F"
photo_percent = 5           ; The percentage of available space occupied by the snap
photo_prealloc_size = 2      ; snap preallocation size (MB)
photo_align_size = 2        ; snap alignment size (MB)

[prealloc]
enable = 0
suffix = ".prealloc"
