#ifndef __PLAYBACKMNG_H__
#define __PLAYBACKMNG_H__

#include "appcomm.h"
#ifdef SERVICES_PLAYER_ON
#include "player_service.h"
#endif

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* End of #ifdef __cplusplus */

#define AMPLIFIER_ON 1
#define AMPLIFIER_OFF 0

/** Error Code */
#define PLAYBACKMNG_EINVAL          APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_EINVAL)                  /**<Invalid argument */
#define PLAYBACKMNG_ENOTINIT        APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_ENOINIT)                 /**<Not inited */
#define PLAYBACKMNG_EINITIALIZED    APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_EINITIALIZED)            /**<Already Initialized */
#define PLAYBACKMNG_EINTER          APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_EINTER)                  /**<Already Initialized */
#define PLAYBACKMNG_EREGISTER_EVENT APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_ERRNO_CUSTOM_BOTTOM)     /**<register event failed */
#define PLAYBACKMNG_EMAXINSTANCE    APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_ERRNO_CUSTOM_BOTTOM + 1) /**<beyond maximum instance */
#define PLAYBACKMNG_ESTORAGE        APP_APPCOMM_ERR_ID(APP_MOD_PLAYBACKMNG, APP_ERRNO_CUSTOM_BOTTOM + 2) /**<storage interface error */

/** event ID define */
typedef enum EVENT_PLAYBACKMNG_E {
    EVENT_PLAYBACKMNG_FINISHED = APPCOMM_EVENT_ID(APP_MOD_PLAYBACKMNG, 0),
    EVENT_PLAYBACKMNG_PLAY,
    EVENT_PLAYBACKMNG_PROGRESS,
    EVENT_PLAYBACKMNG_PAUSE,
    EVENT_PLAYBACKMNG_RESUME,
    EVENT_PLAYBACKMNG_FILE_ABNORMAL,
    EVENT_PLAYBACKMNG_BUTT
} EVENT_PLAYBACKMNG_E;

#ifndef SERVICES_PLAYER_ON
typedef void* PLAYER_SERVICE_HANDLE_T;
typedef enum
{
    PLAYER_SERVICE_EVENT_UNKNOWN,
    PLAYER_SERVICE_EVENT_OPEN_FAILED,
    PLAYER_SERVICE_EVENT_PLAY,
    PLAYER_SERVICE_EVENT_PLAY_FINISHED,
    PLAYER_SERVICE_EVENT_PLAY_PROGRESS,
    PLAYER_SERVICE_EVENT_PAUSE,
    PLAYER_SERVICE_EVENT_RESUME,
    PLAYER_SERVICE_EVENT_RECOVER_START,
    PLAYER_SERVICE_EVENT_RECOVER_PROGRESS,
    PLAYER_SERVICE_EVENT_RECOVER_FAILED,
    PLAYER_SERVICE_EVENT_RECOVER_FINISHED,
} PLAYER_SERVICE_EVENT_TYPE_E;

typedef struct
{
    PLAYER_SERVICE_EVENT_TYPE_E type;
    double value;
} PLAYER_SERVICE_EVENT_S;
#endif

void PLAYBACKMNG_EventCallBack(PLAYER_SERVICE_HANDLE_T hdl, PLAYER_SERVICE_EVENT_S *event_t);
int32_t PLAYBACKMNG_RegisterEvent(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif /* End of __PLAYBACKMNG_H__ */