[work_mode]
poweron_mode = "record"

; vo config
[vo_config]
vo_cnt  = 1

[vo0]
width   = 1920
height  = 440
fps     = -1
rotate  = 1  ; 0:0 1:90 2:180 3:270

; window config
[window_config]
window_cnt  = 2

[window0]
enable      = 1
used_crop   = 1
small_win_enable    = 1
bind_vproc_id       = 0
bind_vproc_chn_id   = 1
x           = 0
y           = 0
width       = 1920
height      = 440
s_x         = 0
s_y         = 0
s_width     = 960
s_height    = 440
onestep     = 20
ystep       = 0
mirror      = 0
filp        = 0

[window1]
enable      = 1
used_crop   = 1
small_win_enable    = 1
bind_vproc_id       = 1
bind_vproc_chn_id   = 1
x           = 0
y           = 0
width       = 1920
height      = 440
s_x         = 960
s_y         = 0
s_width     = 960
s_height    = 440
onestep     = 20
ystep       = 0
mirror      = 0
filp        = 0

; Ai config
[ai]
sample_rate = 16000
channel     = 2
num_per_frm = 640
audio_channel = 1
isVquOn = 0
volume = 20

; Aenc config
[aenc]
format      = 3 ; 0: aac, 3: disable
sample_rate = 16000
num_per_frm = 1024
channel     = 2

; Ao config
[ao]
PowerPinId = 495 ;HAL_GPIOA_15
sample_rate = 16000
channel     = 2
num_per_frm = 320
audio_channel = 1
volume = 32

; Speech config
[speech]
enable      = 1
sample_rate = 16000
bitWidth    = 1 ;; 0: AUDIO_BIT_WIDTH_8; 1: AUDIO_BIT_WIDTH_16; 2: AUDIO_BIT_WIDTH_24; 3: AUDIO_BIT_WIDTH_32
model_path  = "/mnt/data/bin/sound_cardv_sr16k_v5_cv181x.cvimodel"

; record
[record_config]
rec_cnt = 2

[record0]
enable          = 1
sub_video_en = 1
bind_venc_id    = 0
audio_status    = 1
file_type       = 1 ;// 0:MP4, 1:MOV, 2:TS, 3:ES, 4:NONE
split_time      = 60000 ; msec
pre_time        = 0 ; sec
post_time       = 10 ; sec
timelapse_recorder_fps  = 25
timelapse_recorder_gop  = 0
memory_buffer_sec = 0
pre_alloc_unit  = 20 ;//pre allocate unit  MB
short_file_ms = 500
devmodel = "sophgo"

[record0_sub]
sub_bind_venc_id    = 1

[record1]
enable          = 1
sub_video_en = 1
bind_venc_id    = 4
audio_status    = 1
file_type       = 1 ;// 0:MP4, 1:MOV, 2:TS, 3:ES, 4:NONE
split_time      = 60000 ; msec
pre_time        = 0 ; sec
post_time       = 10 ; sec
timelapse_recorder_fps  = 25
timelapse_recorder_gop  = 0
memory_buffer_sec = 0
pre_alloc_unit  = 20 ;//pre allocate unit  MB
short_file_ms = 500
devmodel = "sophgo"

[record1_sub]
sub_bind_venc_id    = 5

; rtsp config
[rtsp_config]
rtsp_cnt    = 2
port=554
timeout=120

[rtsp0]
enable      = 1
bind_venc_id= 1
max_conn = 2
name = "cvi_cam_0";if use cgi, the name should be liveRTSP/av0

[rtsp1]
enable      = 1
bind_venc_id= 5
max_conn = 2
name = "cvi_cam_1";if use cgi, the name should be liveRTSP/av4

; PIV config
[piv_config]
piv_cnt     = 2

[piv0]
bind_venc_id    = 2

[piv1]
bind_venc_id    = 6

; thm config
[thm_config]
thm_cnt     = 2

[thm0]
bind_venc_id    = 3


[thm1]
bind_venc_id    = 7


[photo_config]
photo_cnt     = 2
vprocdev_id   = 1

[photo0]
enable      = 1
bind_venc_id = 2
[photo1]
enable      = 1
bind_venc_id = 6


[motionDet_config]
md_cnt = 2
motionSensitivity = 50

[md0]
enable = 1
bind_vproc_id = 0
bind_vproc_chn_id = 4
[md1]
enable = 1
bind_vproc_id = 1
bind_vproc_chn_id = 4

[adas_config]
adas_cnt = 1
model_fps = 12.5
model_vb_width = 640
model_vb_heigt = 384
car_model_path  = "/mnt/data/bin/vehicle_det.cvimodel"
lane_model_path  = "/mnt/data/bin/lane_det.cvimodel"

[adas0]
enable = 1
bind_vproc_id = 0
bind_vproc_chn_id = 2

[qrcode_config]
qrcode_cnt = 0

[qrcode0]
enable = 1
bind_vproc_id = 0
bind_vproc_chn_id = 5



