; storage config
[storage]
dev_state   = ; 0:unplugged 1:connecting 2:connected 3:idle
stg_state   = ; 0:unplugged 1:connecting 2:error 3:checking ...
fs_type     =
work_mode   =
dev_port    = "cvi.0"
speed_class =
speed_grade =
dev_type    =
dev_path    = "/dev/mmcblk0p1"
mnt_path    = "/mnt/sd/"

[keymng.key]
key_cnt            = 1
key_type0          = 0
key_id0            = 1
longkey_enable0    = 1
longkey_time0      = 2000

[keymng.grpkey]
enable             = 0
key_idx0           = 0
key_idx1           = 1

; wifi
[wifi_config]
enable      = 1 ; 0:disabled 1:enable
mode        = 1 ; 0:STA mode  1: AP mode
ssid        = "cvi_cardv_ap" ; 32 char max
password    = "12345678" ; 32 char max
ssid_hide   = 0 ; 0:hide 1:show
channel     = 6

[pwm_config]
enable       = 1 ; 0:disabled 1:enable
group        = 1 ; mars: pwmchip0/4/8/12
                 ; mars3: pwmchip0/6/12
channel      = 2 ; mars: pwmchip0-pwm0~3 pwmchip4-pwm4~7 pwmchip8-pwm8~11  pwmchip12-pwm12~15
                 ; mars3: pwmchip0-pwm0~5 pwmchip6-pwm6~11 pwmchip12-pwm12~17
period       = 10000 ; unit:ns  100MHz
duty_cycle   = 8000 ;0 ~ 10000

[sensor_config]
dev_num = 2
cam_num = 2
