#ifndef __CMD_RECORD_H__
#define __CMD_RECORD_H__

#define CMD_CLIENT_ID_RECORD (MQ_CLIENT_ID_SCS)
//
// Let CMD_CHANNEL_ID_RECORD equal to servie ID (sensor ID)
//
#define CMD_CHANNEL_ID_RECORD(rec_id) (0x00 + (rec_id))

#ifndef UNUSED
#define UNUSED(x) ((void)(x))
#endif

typedef enum cmd_record_e {
    CMD_RECORD_INVALID = 0,
    CMD_RECORD_SHUTDOWN = 1,
    CMD_RECORD_DEBUG = 2,
    CMD_RECORD_GET_STATUS = 3,
    CMD_RECORD_RESERVED = 4,
    CMD_RECORD_REC_START = 7,
    CMD_RECORD_REC_STOP = 8,
    CMD_RECORD_PIV_CAPTURE = 9,
    CMD_RECORD_LOCK_REC_START = 10,
    CMD_RECORD_LOCK_REC_STOP = 11,
    CMD_RECORD_EVENT_REC = 12,
    CMD_RECORD_RTSP_ENABLE = 13,
    CMD_RECORD_RTSP_DISABLE = 14,
    CMD_RECORD_NULL0 = 17,
    CMD_RECORD_NULL1 = 18,
    CMD_RECORD_RTSP_ADD_FILE_SESSION = 19,
    CMD_RECORD_RTSP_DELETE_FILE_SESSION = 20,
    CMD_RECORD_TIMELAPSE_REC_START = 21,
    CMD_RECORD_TIMELAPSE_REC_STOP = 22,
    CMD_RECORD_MUTE = 23,
    CMD_RECORD_DISABLE_MUTE = 24,
    CMD_RECORD_MAX = 25
} cmd_record_t;

#endif  // __CMD_RECORD_H__
