#ifndef __PLAYER_SERVICE_COMMAND_H__
#define __PLAYER_SERVICE_COMMAND_H__

#define PLAYER_SERVICE_CLIENT_ID (MQ_CLIENT_ID_SVC_0)
#define PLAYER_SERVICE_CHANNEL_ID(chn_id) (0x00 + (chn_id))

#ifndef UNUSED
#define UNUSED(x) ((void)(x))
#endif

typedef enum {
    CMD_PLAYER_INVALID = 0,
    CMD_PLAYER_SHUTDOWN,
    CMD_PLAYER_DEBUG,
    CMD_PLAYER_GET_STATUS,
    CMD_PLAYER_PLAY,
    CMD_PLAYER_STOP,
    CMD_PLAYER_PAUSE,
    CMD_PLAYER_SEEK,
    CMD_PLAYER_RESET_SIZE,
    CMD_PLAYER_RESET_POS,
    CMD_PLAYER_MAX
} PLAYER_SERVICE_COMMAND_E;

#endif // __PLAYER_SERVICE_COMMAND_H__
