import os
import copy

BIN_DIR = os.environ['BIN_DIR'];
LIB_DIR = os.environ['LIB_DIR'];

env = DefaultEnvironment().Clone()
SOURCES = [
  # 'mouse_thread.c', 
  # 'input_thread.c', 
  'input_dispatcher.c', 
  'lcd_linux_fb.c', 
  'lcd_linux_drm.c', 
  'lcd_mem_others.c' ,
  'main_loop_linux.c' ]

TOUCHPAD = os.environ.get('TOUCHPAD')
if TOUCHPAD == 'y':
  print("tslib_thread.c")
  SOURCES = ['tslib_thread.c'] + SOURCES;


env.Library(os.path.join(LIB_DIR, 'awtk_linux_fb'), SOURCES, LIBS=[])
